//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCTerraria {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class IndigoIRC : global::System.Configuration.ApplicationSettingsBase {
        
        private static IndigoIRC defaultInstance = ((IndigoIRC)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IndigoIRC())));
        
        public static IndigoIRC Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("irc.esper.net")]
        public string host {
            get {
                return ((string)(this["host"]));
            }
            set {
                this["host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6667")]
        public int port {
            get {
                return ((int)(this["port"]));
            }
            set {
                this["port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IRCTerraria_Client")]
        public string nick {
            get {
                return ((string)(this["nick"]));
            }
            set {
                this["nick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IRCTerraria")]
        public string name {
            get {
                return ((string)(this["name"]));
            }
            set {
                this["name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ExampleChannel")]
        public string channel {
            get {
                return ((string)(this["channel"]));
            }
            set {
                this["channel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mypassword")]
        public string auth {
            get {
                return ((string)(this["auth"]));
            }
            set {
                this["auth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USER IndigoIRCBot 0 * :IndigoIRC")]
        public string user {
            get {
                return ((string)(this["user"]));
            }
            set {
                this["user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[IRC] %NAME%> ")]
        public string ingameFormatting {
            get {
                return ((string)(this["ingameFormatting"]));
            }
            set {
                this["ingameFormatting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255;117;117")]
        public string ingameColour {
            get {
                return ((string)(this["ingameColour"]));
            }
            set {
                this["ingameColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%NAME%> ")]
        public string ircFormatting {
            get {
                return ((string)(this["ircFormatting"]));
            }
            set {
                this["ircFormatting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string commandPrefix {
            get {
                return ((string)(this["commandPrefix"]));
            }
            set {
                this["commandPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#@")]
        public string ignoredPrefixes {
            get {
                return ((string)(this["ignoredPrefixes"]));
            }
            set {
                this["ignoredPrefixes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!$")]
        public string ignoredIrcPrefixes {
            get {
                return ((string)(this["ignoredIrcPrefixes"]));
            }
            set {
                this["ignoredIrcPrefixes"] = value;
            }
        }
    }
}
